<?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/item.js','text/javascript'); ?>

<!-- START TO DELETE  -->

<script type="text/javascript">
$(document).ready(function() {
	$('input,select').removeClass('noEditedYet');

	$('input,select').change(function(){
		$(this).addClass('noEditedYet');
	});
	
	var table = "<tr><td colspan='10'>"+ $('#features_list_table').html() +"</td></tr>";

	$('#features_list_table').remove();
	
	$("tbody").prepend(table);

	addDetailsRow();
	
	$('#add_features').click(function(){
		addDetailsRow();
	});
	
	$(document).on('click', "input.delete_features", function () {
		$('#row_' + $(this).attr('row')).remove();
	});
});

function addDetailsRow()
{
	var rootPath = $('#SYSTEM_ROOT_PATH').val();

	var detailRowIndex = $('#detail_rows_number').val();
	$('#detail_rows_number').val( Number(detailRowIndex) + 1 );

	$.ajax({
        url: rootPath + "item/ajaxloaddetails",
        type: 'POST',
		data: { rowNumber: detailRowIndex
				},
        success: function(response)
		{
        	$('#features_list').append( response );
        },
        error: function(request, textStatus, errorThrown)
		{
            var message = (request.status == 403) ? request.responseText : message;
            alert("Error retrieving select data - " + message);
        }
    });

	
}


//<tr><td><input type='text' name='auxiliar' id='auxiliar' value='This data arrive!!'/></td></tr>
</script>

<style>
.noEditedYet {
	background: #8CDCB4;
}
</style>

<!-- END TO DELETE  -->
<h1>Agregar item:</h1>

<a href='<?php echo $this->url ( array (
					'controller' => 'item',
					'action' => 'index' 
						), 'default', true )?>'>
						<img src="<?php echo $this->rootPath ?>images/back.png" title="VOLVER AL LISTADO" border="0"> Volver al listado</a>

<br/>

<div id='features_list_table'>
	<table id='features_list' align='center'>
		<tr>
			<td><input type='button' id='add_features' value='Agregar'/></td>
		</tr>
		<tr>
			<th>COLOR</th>
			<th>TALLA</th>
			<th>CANTIDAD</th>
			<th></th>
		</tr>
		<?php ?>
		<tr id='row_<?php echo $this->rowNumber; ?>'>
			<td><?php echo $this->colorSelect; ?></td>
			<td><?php echo $this->sizeSelect; ?></td>
			<td><input type='text' name='quantity_<?php echo $this->rowNumber; ?>' id='quantity_<?php echo $this->rowNumber; ?>' class='css-input_number_form' value='0'/></td>
			<td><input type='button' class='delete_features' row='<?php echo $this->rowNumber; ?>' value='Borrar'/></td>
		</tr>
		<?php ?>
	</table>
</div>

<div align="center">
	<?php echo $this->form; ?>
</div>

<div align="center">
	<?php echo $this->message; ?>
</div>