<h1>Item:</h1>

<a href='<?php echo $this->url ( array (
					'controller' => 'item',
					'action' => 'index' 
						), 'default', true )?>'>
						<img src="<?php echo $this->rootPath ?>images/back.png" title="VOLVER AL LISTADO" border="0"> Volver al listado</a>

<br/>

<table border="0" align="center">
<tr>
	<th align="right">Tipo:</th>
	<td><?php echo $this->item->getType()->getName(); ?></td>
</tr>
<tr>
	<th align="right">Marca:</th>
	<td><?php echo $this->item->getBrand()->getName(); ?></td>
</tr>
<tr>
	<th align="right">Talla:</th>
	<td><?php echo $this->item->getSize()->getName(); ?></td>
</tr>
<tr>
	<th align="right">Color:</th>
	<td><?php echo $this->item->getColor()->getName(); ?></td>
</tr>
<tr>
	<th align="right">Cantidad:</th>
	<td><?php echo $this->item->getQuantity(); ?></td>
</tr>
<tr>
	<th align="right">Precio unid.:</th>
	<td><?php echo $this->item->getPrice(); ?></td>
</tr>
<tr>
	<th align="right">Precio final unid.:</th>
	<td><?php echo $this->item->getFinalPrice(); ?></td>
</tr>
<tr>
	<th align="right">Descripci&oacute;n:</th>
	<td><p><?php echo str_replace(chr(13), "<br/>", $this->item->getDescription()); ?></p></td>
</tr>
<tr>
	<th align="right">Procedencia:</th>
	<td><?php echo $this->item->getOrigin()->getName(); ?></td>
</tr>
<tr>
	<th align="right">C&oacute;digo:</th>		
	<td><?php echo $this->item->getCode(); ?></td>
</tr>
<tr>
	<th align="right">Costo de venta:</th>
	<td><?php echo $this->item->getCost(); ?></td>
</tr>
<tr>
	<td align="center" colspan="2">
		<a href='<?php echo $this->url ( array (
					'controller' => 'item',
					'action' => 'edit', 
					'id' => $this->item->getId()
						), 'default', true )?>'>EDITAR DATOS</a>
	</td>
</tr>
</table>

<div id="item_images" class="css-div-images">
	<?php
	$folder = $this->photosPath . $this->item->getPhotoDir() . '/';
	$filetype = '*.*';
	$files = glob($folder . $filetype);
	
	for ($i=0; $i<count($files); $i++) {
		echo "<img src='" . $this->rootPath . "/" . $files[$i] . "' />";
	}
	?>
</div>