

<script type="text/javascript">
$(document).ready(function() {
	$('#search_code').keyup(function(){
		loadResultsTable();
	});

	$('.search_component').change(function(){
		loadResultsTable();
	});
});

function loadResultsTable()
{
	var rootPath = $('#SYSTEM_ROOT_PATH').val();
	
	$.ajax({
        url: rootPath + "sales/ajaxfinditem",
        type: 'POST',
        async: 'false',
		data: { brand: $('#brand_select_search').val(),
				type: $('#type_select_search').val(),
				size: $('#size_select_search').val(),
				color: $('#color_select_search').val(),
				code: $('#search_code').val()
				},
        success: function(resultsTable)
		{
        	$('#search_panel').html( resultsTable );
        },
        error: function(request, textStatus, errorThrown)
		{
            var message = (request.status == 403) ? request.responseText : message;
            alert("Error retrieving search_text data - " + message);
        }
    });
}

</script>


<div id='content_left'>
	<table class='css-table-search' align='center'>
		<tr>
			<th colspan='2'>BUSCADOR</th>
		<tr>
			<th>C&oacute;digo</th>
			<td><input type='text' id=search_code name='search_code' value=''/></td>
		</tr>
		<tr>
			<th>Tipo</th>
			<td><?php echo $this->typeSelect; ?></td>
		</tr>
		<tr>
			<th>Marca</th>
			<td><?php echo $this->brandSelect; ?></td>
		</tr>
		<tr>
			<th>Talla</th>
			<td><?php echo $this->sizeSelect; ?></td>
		</tr>
		<tr>
			<th>Color</th>
			<td><?php echo $this->colorSelect; ?></td>
		</tr>					
	</table>
</div>
<div id='search_panel'>
</div>