
<script type="text/javascript">
var rootPath = $('#SYSTEM_ROOT_PATH').val();
var row = -1;

$(document).ready(function() {
	$('#search_code').keyup(function(){
		loadResultsTable();
	});

	$('.search_component').change(function(){
		loadResultsTable();
	});

	$('#sale_date').datepicker({
		maxDate: 0,
		dateFormat: 'dd-M-yy',
		showAnim: 'slide',
		showOn: 'button',
		buttonImage: '../images/calendar.gif',
		buttonImageOnly: true,
		changeMonth: true,
		changeYear: true,
		onSelect: function(value, date)
		{
			$('#date_panel').html(' ' + value);
			//$('#sale_date').val(value);

			var date = $(this).datepicker('getDate'),
            day  = date.getDate(),  
            month = date.getMonth() + 1,              
            year =  date.getFullYear();
			$('#sale_date').val(day + '-' + month + '-' + year);
		} 
	});

	$(document).on('click', "a.item_to_sale", function () {
		row = Number(row) + 1;
		$('#sale_index_row').val(row);

		$.ajax({
	        url: rootPath + "sales/ajaxaddsaleitem",
	        type: 'POST',
	        async: 'false',
			data: { id: $(this).attr('item_code'),
					row: row
					},
	        success: function(itemAdded)
			{
	        	$('#sales_tables').prepend('</br>');
	        	$('#sales_tables').prepend( itemAdded );
	        	$('#sale_reserved_' + row ).hide();
	        },
	        error: function(request, textStatus, errorThrown)
			{
	            var message = (request.status == 403) ? request.responseText : message;
	            alert("Error retrieving search_text data - " + message);
	        }
	    });
	});

	$(document).on('click', "input.delete_button", function () {
		if (confirm("Desea QUITAR el item de la lista de venta???") == true)
			$('#sale_table_' + $(this).attr('row')).remove();		
	});

	$(document).on('change', "select.sale_type", function () {
		var row = $(this).attr('row');

		// If is reserved type
		if( $(this).val() == '2' )
		{
			$('#sale_anticipated_payment_' + row).val('0.00');
			$('#sale_debt_' + row).html('0.00');
			$('#sale_reserved_' + row).show();
		}	
		else
			$('#sale_reserved_' + row).hide();
	});

	$(document).on('keyup', "input.sale_total_calculate", function () {
		var row = $(this).attr('row');
		
		validateInputText(this);

		var total = Number($('#sale_quantity_' + row).val()) * Number($('#sale_unit_price_' + row).val());
		$('#sale_total_' + row).html(total.toFixed(2));				
	});

	$(document).on('keyup', "input.sale_debt_calculate", function () {
		var row = $(this).attr('row');
		
		if($('#sale_reserved_' + row).is(":visible") && $('#sale_anticipated_payment_' + row).val() > 0)
		{
			validateInputText(this);

			var debt = (Number($('#sale_quantity_' + row).val()) * Number($('#sale_unit_price_' + row).val())) - Number($('#sale_anticipated_payment_' + row).val());
			$('#sale_debt_' + row).html(debt.toFixed(2));
		}
	});
});

function loadResultsTable()
{
	$.ajax({
        url: rootPath + "sales/ajaxfinditem",
        type: 'POST',
        async: 'false',
		data: { brand: $('#brand_select_search').val(),
				type: $('#type_select_search').val(),
				size: $('#size_select_search').val(),
				color: $('#color_select_search').val(),
				code: $('#search_code').val()
				},
        success: function(resultsTable)
		{
        	$('#search_panel').html( resultsTable );
        },
        error: function(request, textStatus, errorThrown)
		{
            var message = (request.status == 403) ? request.responseText : message;
            alert("Error retrieving search_text data - " + message);
        }
    });
}

</script>


<div id='content_left'>
	<table class='css-table-search' align='center'>
		<tr>
			<th colspan='2'>BUSCADOR</th>
		<tr>
			<th>C&oacute;digo</th>
			<td><input type='text' id=search_code name='search_code' value=''/></td>
		</tr>
		<tr>
			<th>Tipo</th>
			<td><?php echo $this->typeSelect; ?></td>
		</tr>
		<tr>
			<th>Marca</th>
			<td><?php echo $this->brandSelect; ?></td>
		</tr>
		<tr>
			<th>Talla</th>
			<td><?php echo $this->sizeSelect; ?></td>
		</tr>
		<tr>
			<th>Color</th>
			<td><?php echo $this->colorSelect; ?></td>
		</tr>					
	</table>
</div>

<div id='search_panel' class="css-search_div_panel">
</div>

</br>

<form action="" method="post" enctype="application/x-www-form-urlencoded">

<div class='css-container_inline'>
	<h2>Compras:</h2>
	<h2 id='date_panel'> <?php echo Date('d-M-Y'); ?></h2>
	<input id='sale_date' name='sale_date' type='hidden' readonly="readonly" value='<?php echo Date('d-m-Y'); ?>' />
</div>

<div align='center' id='sales_tables'></div>

<input type='hidden' name='sale_index_row' id='sale_index_row' value='-1' />

<div align='center'>
	<input type='submit' value='ACEPTAR' />
</div>

</form>